version: '3'
services:

  postgres:
   image: postgres:16beta1-alpine3.17
   restart: always
   container_name: postgres
   ports:
   - 5432:5432
   volumes:
      - ./postgres/data:/var/lib/postgresql/data
   env_file:
   - .env
   networks:
   - my-pg-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
       - ./pgadmin/data:/var/lib/pgadmin
    ports:
      - 3001:80
    restart: unless-stopped
    networks:
      - my-pg-network


networks:
   my-pg-network:
    driver: bridge
