---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Поднимаем контейнер nginx
      become: true
      block:
        - name: Create a nginx container
          community.docker.docker_container:
            name: nginx
            image: nginx:1.13
            state: started
            ports:
              - "8080:80"
        - name: Копируем файл index.html
          community.docker.docker_container_copy_into:
            container: nginx
            path: index.html
            container_path: /usr/share/nginx/html
        - name: Копируем файл nginx.conf
          community.docker.docker_container_copy_into:
            container: nginx
            path: nginx.conf
            container_path: /etc/nginx/conf.d/default.conf
